version: "3"

services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: quero_alugar_development
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - queroalugar

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    env_file: .env
    environment:
      RAILS_ENV: development
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: password
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    networks:
      - queroalugar

  redis:
    image: redis:6.2.7
    networks:
      - queroalugar

  sidekiq:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/opt/app
    ports:
      - '3032:3032'
    env_file: .env
    environment:
      RAILS_ENV: development
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: password
    entrypoint: ./docker/entrypoints/sidekiq-entrypoint.sh
    tty: true
    stdin_open: true
    networks:
      - queroalugar

networks:
  queroalugar:
    driver: bridge

volumes:
  db-data:
    driver: local
    external: false
